#!/usr/bin/env python3

/usr/bin/env: ‘python3\r’: No such file or directory
https://askubuntu.com/questions/896860/usr-bin-env-python3-r-no-such-file-or-directory

sudo apt install dos2unix
dos2unix test.py

xacro spawn하니... 에러가 나버리고 시간이 멈춰버린다...

model:// 태그 때문에 안되는 것임 => https://answers.gazebosim.org//question/26073/cannot-spawn-urdf-into-gazebo-using-ros2/

gz sdf -p fusionbot.urdf > fusionbot.sdf

models 폴더 만들고 여기 안에 mesh 넣는다.
model.sdf => 맨 위에 <?xml version='1.0'?> / model://fusionbot/meshes => model://fusionbot/meshes/fusionbot
model.config 넣는다.

시간이 멈춰버리고 아무것도 안됨 ㅠㅠ => ros launch로 안켜서 그런 것임

add path가 되니까 그냥 urdf 스폰으로 가자

install(DIRECTORY launch meshes urdf rviz models
  DESTINATION  share/${PROJECT_NAME}
)

 ros2 launch fusionbot_description fusionbot_gazebo.launch.py
=> 잘된다~~ ㅅㅂ ㅠㅠ

색깔 바꿀까?? 흠...

